ALTER TABLE users ADD COLUMN max_active_backtests INTEGER NOT NULL DEFAULT 10;
ALTER TABLE users ADD COLUMN max_strategies INTEGER NOT NULL DEFAULT 10;
ALTER TABLE users ADD COLUMN max_bot_instances INTEGER NOT NULL DEFAULT 10;
