apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dydx-next-staging
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/environment: staging
patches:
  - path: patch-platform-config.yaml
  - path: patch-ingress-hosts.yaml
  - path: patch-replicas.yaml
