#!/bin/bash
# Alembic Make Commands - Usage Examples

echo "═══════════════════════════════════════════════════════════════"
echo "  ALEMBIC DATABASE MIGRATION COMMANDS - COMPLETE SETUP ✅"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📋 COMMANDS ADDED TO MAKEFILE (9 total)"
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "🔧 CORE MIGRATION COMMANDS"
echo "   make db-upgrade                           Apply all pending migrations"
echo "   make db-revision MESSAGE='description'    Create new migration"
echo "   make db-downgrade STEPS=1                 Rollback migrations"
echo ""

echo "📊 STATUS COMMANDS"
echo "   make db-current                           Show current migration version"
echo "   make db-history                           Show all applied migrations"
echo "   make db-branches                          Check for conflicting branches"
echo ""

echo "⚙️  ADVANCED COMMANDS"
echo "   make db-merge MESSAGE='description'       Merge conflicting migrations"
echo "   make db-migrate-legacy                    Run old SQLite migration"
echo "   make db-init                              Initialize Alembic (one-time)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  QUICK START GUIDE"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "Step 1: Activate Virtual Environment"
echo "   $ source .venv/bin/activate"
echo ""

echo "Step 2: Apply Database Migrations"
echo "   $ make db-upgrade"
echo ""

echo "Step 3: Verify Current Version"
echo "   $ make db-current"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  COMMON WORKFLOWS"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "✅ NEW DEVELOPER SETUP"
echo "   1. make db-upgrade              # Apply all pending migrations"
echo "   2. make db-current              # Verify current version"
echo ""

echo "✅ ADD NEW DATABASE COLUMN"
echo "   1. make db-revision MESSAGE='add_email_column'"
echo "   2. cat alembic/versions/      # Review generated migration"
echo "   3. make db-upgrade             # Apply it"
echo ""

echo "✅ CHECK PENDING MIGRATIONS"
echo "   $ make db-history"
echo ""

echo "✅ ROLLBACK LAST MIGRATION"
echo "   $ make db-downgrade STEPS=1"
echo ""

echo "✅ MERGE CONFLICTING MIGRATIONS (team)"
echo "   1. make db-branches             # Check for conflicts"
echo "   2. make db-merge MESSAGE='fix'  # Merge branches"
echo "   3. make db-upgrade              # Apply merged migration"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  EXAMPLE: CREATE AND APPLY NEW MIGRATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "# Create migration for new user profile"
echo "$ make db-revision MESSAGE='add user profile fields'"
echo ""
echo "# This creates: alembic/versions/abc123def456_add_user_profile_fields.py"
echo ""
echo "# Review the generated file:"
echo "$ cat alembic/versions/abc123def456_add_user_profile_fields.py"
echo ""
echo "# Apply it to the database:"
echo "$ make db-upgrade"
echo ""
echo "# Verify it was applied:"
echo "$ make db-current"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "❌ \"Target database is not up to date\""
echo "   → Fix: make db-upgrade"
echo ""

echo "❌ \"Multiple heads detected\""
echo "   → Fix: make db-merge MESSAGE='resolve branches' && make db-upgrade"
echo ""

echo "❌ \"Database is locked\" (SQLite)"
echo "   → Fix: rm -f app/dydx_backtest.db-journal && make db-upgrade"
echo ""

echo "❌ Parameter missing error"
echo "   → Fix: Check usage in error message"
echo "   → make db-revision MESSAGE='x'    (must have MESSAGE)"
echo "   → make db-downgrade STEPS=1       (must have STEPS)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  FILES MODIFIED"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✏️  Makefile"
echo "    ├─ Added 9 db-* commands"
echo "    ├─ New section: DATABASE & MIGRATIONS (Alembic)"
echo "    └─ Updated .PHONY for new targets"
echo ""
echo "📄 DB_COMMANDS.md (created - quick reference)"
echo "   └─ Commands, workflows, troubleshooting"
echo ""
echo "📄 ALEMBIC_GUIDE.md (created - detailed guide)"
echo "   └─ Complete documentation with examples"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  VERIFICATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "To see all database commands:"
echo "   $ make help | grep db-"
echo ""
echo "To see all available make targets:"
echo "   $ make help"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  ALEMBIC BASICS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Alembic is SQLAlchemy's database migration tool"
echo ""
echo "Key Concepts:"
echo "  • Migration: A Python script that alters database schema"
echo "  • Head: Latest applied migration version"
echo "  • Revision: A unique ID for each migration"
echo "  • Downgrade: Reverting a migration (if reversible)"
echo ""
echo "Migration Files Live In: alembic/versions/"
echo ""
echo "Current Migrations:"
ls -1 alembic/versions/*.py 2>/dev/null | xargs -I {} basename {} || echo "   (none yet)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✅ SETUP COMPLETE - Ready to use!"
echo "═══════════════════════════════════════════════════════════════"
