version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly
  go: "1.25"

output:
  formats:
    text:
      path: stdout
  show-stats: true

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - errname
    - govet
    - ineffassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused
    - wastedassign

  exclusions:
    paths:
      - vendor
      - .idea
      - migrations
      - ".*\\.pb\\.go$"
      - ".*_generated\\.go$"

issues:
  uniq-by-line: true
  max-issues-per-linter: 0
  max-same-issues: 0
