services:
  redis-master-proxy:
    image: bitnamilegacy/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
    networks:
      internal:
        aliases:
          - redis-master-proxy
          - redis
    volumes:
      - redis_data:/bitnami/redis/data
    secrets:
      - redis_password
    healthcheck:
      test:
        ["CMD-SHELL", 'redis-cli -a "$$(cat /run/secrets/redis_password)" ping']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  internal:
    external: true

volumes:
  redis_data:

secrets:
  redis_password:
    external: true
