services:
  redis-master-proxy:
    image: bitnamilegacy/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
    networks:
      internal:
        aliases:
          - redis-master-proxy
          - redis
    volumes:
      - redis_data:/bitnami/redis/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  internal:
    external: true

volumes:
  redis_data:
