"""Add BacktestStrategy and BacktestComparison tables

Revision ID: 01a39f021b09
Revises: 
Create Date: 2025-10-19 02:47:22.740654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a39f021b09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.add_column('backtest_runs', sa.Column('strategy_snapshot', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_foreign_key(None, 'backtest_runs', 'backtest_strategies', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'backtest_runs', type_='foreignkey')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_column('backtest_runs', 'strategy_snapshot')
    op.drop_column('backtest_runs', 'strategy_id')
    # ### end Alembic commands ###
