"""add_resolution_column_to_backtest_runs

Revision ID: 782e23245ee3
Revises: 709f38577735
Create Date: 2025-10-23 21:49:13.379337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782e23245ee3'
down_revision: Union[str, None] = '709f38577735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('resolution', sa.String(length=20), server_default='1HOUR', nullable=False))
    op.alter_column('backtest_strategies', 'initial_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Initial investment amount (USD) allocated to this strategy',
               existing_nullable=False,
               existing_server_default=sa.text("'1000'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backtest_strategies', 'initial_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Initial investment amount (USD) allocated to this strategy',
               existing_nullable=False,
               existing_server_default=sa.text("'1000'::double precision"))
    op.drop_column('backtest_runs', 'resolution')
    # ### end Alembic commands ###
