"""add backtest candle table for ohlcv data storage

Revision ID: c4fd4922843f
Revises: add_dydx_keys_table
Create Date: 2025-10-20 19:47:48.398369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fd4922843f'
down_revision: Union[str, None] = 'add_dydx_keys_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
