INSERT IGNORE INTO bot_settings (
  section,
  `key`,
  value,
  value_type,
  description,
  default_value,
  is_active,
  version,
  created_at,
  updated_at
)
VALUES
  (
    'platform',
    'crm_subdomain_enabled',
    '1',
    'boolean',
    'Enable CRM subdomain routing shortcuts',
    '1',
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'platform',
    'crm_subdomain_host',
    'crm.localhost',
    'string',
    'CRM subdomain host used for cross-portal links',
    'crm.localhost',
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'platform',
    'ib_subdomain_enabled',
    '1',
    'boolean',
    'Enable IB portal subdomain routing shortcuts',
    '1',
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'platform',
    'ib_subdomain_host',
    'ib-portal.localhost',
    'string',
    'IB portal subdomain host used for cross-portal links',
    'ib-portal.localhost',
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );
