dydx:
 dydx_chain_address: ""
 dydx_secret_phrase: ""
 is_testnet: false
telegram:
  token: ""
  chat_id: ""
botSettings:
  abortAllPositions: true
  findCointegratedPairs: true
  manageExits: true
  placeTrades: true
  resolutionTimeframe: "1HOUR"
  strategy: "cointegration"
  statsWindow: 21 
  # Thresholds - Opening
  maxHalfLife: 24
  ZScoreThreshold: 1.5
  usdPerTrade: 10
  usdMinCollateral: 100
  # Thresholds - Closing
  closeAtZscoreCross: true
  indexer_endpoint:
    testnet: "https://indexer.v4testnet.dydx.exchange"
    mainnet: "https://indexer.dydx.trade"
    
