"""Initial database schema

Revision ID: 66f08c3b1066
Revises: 
Create Date: 2025-11-02 00:37:36.891785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f08c3b1066'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'STARTING', 'RUNNING', 'PAUSED', 'STOPPING', 'STOPPED', 'FAILED', 'ERROR', name='botstatusenum'), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('process_started_at', sa.DateTime(), nullable=True),
    sa.Column('process_ended_at', sa.DateTime(), nullable=True),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=128), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('usd_per_trade', sa.Float(), nullable=True),
    sa.Column('zscore_threshold', sa.Float(), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('successful_trades', sa.Integer(), nullable=True),
    sa.Column('failed_trades', sa.Integer(), nullable=True),
    sa.Column('total_profit_loss', sa.Float(), nullable=True),
    sa.Column('wallet_address', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_created', 'bot_instances', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_instances_instance_id'), 'bot_instances', ['instance_id'], unique=True)
    op.create_index('ix_bot_status', 'bot_instances', ['status'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_bots_running', sa.Integer(), nullable=True),
    sa.Column('total_active_trades', sa.Integer(), nullable=True),
    sa.Column('total_profit_loss', sa.Float(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('memory_usage_percent', sa.Float(), nullable=True),
    sa.Column('database_size_mb', sa.Float(), nullable=True),
    sa.Column('connection_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_timestamp', 'system_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_instance_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('trades_opened', sa.Integer(), nullable=True),
    sa.Column('trades_closed', sa.Integer(), nullable=True),
    sa.Column('successful_trades', sa.Integer(), nullable=True),
    sa.Column('failed_trades', sa.Integer(), nullable=True),
    sa.Column('daily_profit_loss', sa.Float(), nullable=True),
    sa.Column('cumulative_profit_loss', sa.Float(), nullable=True),
    sa.Column('jobs_completed', sa.Integer(), nullable=True),
    sa.Column('jobs_failed', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_instance_id'], ['bot_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_index('ix_report_bot_date', 'daily_reports', ['bot_instance_id', 'report_date'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_instance_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('related_job_id', sa.String(length=64), nullable=True),
    sa.Column('related_trade_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_instance_id'], ['bot_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_bot_id', 'event_logs', ['bot_instance_id'], unique=False)
    op.create_index('ix_event_created', 'event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_logs_created_at'), 'event_logs', ['created_at'], unique=False)
    op.create_index('ix_event_type', 'event_logs', ['event_type'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('bot_instance_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRY', name='jobstatusenum'), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('process_started_at', sa.DateTime(), nullable=True),
    sa.Column('process_ended_at', sa.DateTime(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_used_mb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_instance_id'], ['bot_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_bot_id', 'jobs', ['bot_instance_id'], unique=False)
    op.create_index('ix_job_created', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_job_status', 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('bot_instance_id', sa.Integer(), nullable=False),
    sa.Column('pair1', sa.String(length=32), nullable=False),
    sa.Column('pair2', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPENED', 'PARTIALLY_CLOSED', 'CLOSED', 'FAILED', 'CANCELLED', name='tradestatusenum'), nullable=False),
    sa.Column('entry_price1', sa.Float(), nullable=True),
    sa.Column('entry_price2', sa.Float(), nullable=True),
    sa.Column('entry_size1', sa.Float(), nullable=True),
    sa.Column('entry_size2', sa.Float(), nullable=True),
    sa.Column('exit_price1', sa.Float(), nullable=True),
    sa.Column('exit_price2', sa.Float(), nullable=True),
    sa.Column('exit_size1', sa.Float(), nullable=True),
    sa.Column('exit_size2', sa.Float(), nullable=True),
    sa.Column('entry_cost', sa.Float(), nullable=True),
    sa.Column('exit_proceeds', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_loss_percentage', sa.Float(), nullable=True),
    sa.Column('entry_fees', sa.Float(), nullable=True),
    sa.Column('exit_fees', sa.Float(), nullable=True),
    sa.Column('entry_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('exit_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('dydx_position_id', sa.String(length=128), nullable=True),
    sa.Column('zscore_entry', sa.Float(), nullable=True),
    sa.Column('half_life_days', sa.Float(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bot_instance_id'], ['bot_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_bot_id', 'trades', ['bot_instance_id'], unique=False)
    op.create_index('ix_trade_opened', 'trades', ['opened_at'], unique=False)
    op.create_index('ix_trade_status', 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index('ix_trade_status', table_name='trades')
    op.drop_index('ix_trade_opened', table_name='trades')
    op.drop_index('ix_trade_bot_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index('ix_job_status', table_name='jobs')
    op.drop_index('ix_job_created', table_name='jobs')
    op.drop_index('ix_job_bot_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_event_type', table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_created_at'), table_name='event_logs')
    op.drop_index('ix_event_created', table_name='event_logs')
    op.drop_index('ix_event_bot_id', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('ix_report_bot_date', table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index('ix_metrics_timestamp', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index('ix_bot_status', table_name='bot_instances')
    op.drop_index(op.f('ix_bot_instances_instance_id'), table_name='bot_instances')
    op.drop_index('ix_bot_created', table_name='bot_instances')
    op.drop_table('bot_instances')
    # ### end Alembic commands ###
