"""initial schema creation

Revision ID: 77959b2d7de6
Revises: 
Create Date: 2025-10-26 22:28:01.146352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77959b2d7de6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redis_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('db', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('ssl', sa.Boolean(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('max_connections', sa.Integer(), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('cache_backtest_results', sa.Boolean(), nullable=True),
    sa.Column('cache_market_data', sa.Boolean(), nullable=True),
    sa.Column('cache_analysis_results', sa.Boolean(), nullable=True),
    sa.Column('last_connection_test', sa.DateTime(), nullable=True),
    sa.Column('last_connection_status', sa.String(length=20), nullable=True),
    sa.Column('total_cache_hits', sa.Integer(), nullable=True),
    sa.Column('total_cache_misses', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redis_enabled', 'redis_settings', ['enabled'], unique=False)
    op.create_index(op.f('ix_redis_settings_enabled'), 'redis_settings', ['enabled'], unique=False)
    op.create_index(op.f('ix_redis_settings_id'), 'redis_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('backtest_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('zscore_threshold', sa.Float(), nullable=False),
    sa.Column('stats_window', sa.Integer(), nullable=False),
    sa.Column('max_half_life', sa.Float(), nullable=False),
    sa.Column('usd_per_trade', sa.Float(), nullable=False),
    sa.Column('usd_min_collateral', sa.Float(), nullable=False),
    sa.Column('close_at_zscore_cross', sa.Boolean(), nullable=False),
    sa.Column('find_cointegrated_pairs', sa.Boolean(), nullable=False),
    sa.Column('manage_exits', sa.Boolean(), nullable=False),
    sa.Column('place_trades', sa.Boolean(), nullable=False),
    sa.Column('abort_all_positions', sa.Boolean(), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('take_profit_pct', sa.Float(), nullable=False),
    sa.Column('trailing_stop_pct', sa.Float(), nullable=False),
    sa.Column('rebalance_interval_hours', sa.Integer(), nullable=False),
    sa.Column('position_timeout_hours', sa.Integer(), nullable=False),
    sa.Column('transaction_fee', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('candle_resolution', sa.String(length=20), nullable=False),
    sa.Column('max_history_days', sa.Integer(), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=20), nullable=True),
    sa.Column('risk_free_rate', sa.Float(), nullable=False),
    sa.Column('initial_amount', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_category', 'backtest_strategies', ['category'], unique=False)
    op.create_index('idx_strategy_default', 'backtest_strategies', ['is_default'], unique=False)
    op.create_index('idx_strategy_public', 'backtest_strategies', ['is_public'], unique=False)
    op.create_index('idx_strategy_user_name', 'backtest_strategies', ['user_id', 'name'], unique=False)
    op.create_index(op.f('ix_backtest_strategies_created_at'), 'backtest_strategies', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_strategies_id'), 'backtest_strategies', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_strategies_name'), 'backtest_strategies', ['name'], unique=False)
    op.create_index(op.f('ix_backtest_strategies_user_id'), 'backtest_strategies', ['user_id'], unique=False)
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bot_setting_active', 'bot_settings', ['is_active'], unique=False)
    op.create_index('idx_bot_setting_section_key', 'bot_settings', ['section', 'key'], unique=False)
    op.create_index(op.f('ix_bot_settings_id'), 'bot_settings', ['id'], unique=False)
    op.create_index(op.f('ix_bot_settings_is_active'), 'bot_settings', ['is_active'], unique=False)
    op.create_index(op.f('ix_bot_settings_key'), 'bot_settings', ['key'], unique=False)
    op.create_index(op.f('ix_bot_settings_section'), 'bot_settings', ['section'], unique=False)
    op.create_table('dydx_key_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_network', sa.String(length=50), nullable=False),
    sa.Column('auto_switch_testnet', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dydx_key_settings_id'), 'dydx_key_settings', ['id'], unique=False)
    op.create_index(op.f('ix_dydx_key_settings_user_id'), 'dydx_key_settings', ['user_id'], unique=True)
    op.create_table('dydx_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('chain_address', sa.String(length=255), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'network', name='uq_user_network_keys')
    )
    op.create_index(op.f('ix_dydx_keys_id'), 'dydx_keys', ['id'], unique=False)
    op.create_index(op.f('ix_dydx_keys_network'), 'dydx_keys', ['network'], unique=False)
    op.create_index(op.f('ix_dydx_keys_user_id'), 'dydx_keys', ['user_id'], unique=False)
    op.create_table('strategy_execution_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('trades_executed', sa.Integer(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('last_started', sa.DateTime(), nullable=True),
    sa.Column('last_stopped', sa.DateTime(), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('last_cointegration_check', sa.DateTime(), nullable=True),
    sa.Column('active_pairs_count', sa.Integer(), nullable=True),
    sa.Column('open_positions_count', sa.Integer(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['backtest_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_state_status', 'strategy_execution_states', ['strategy_id', 'status'], unique=False)
    op.create_index('idx_execution_state_strategy_enabled', 'strategy_execution_states', ['strategy_id', 'enabled'], unique=False)
    op.create_index('idx_execution_state_updated', 'strategy_execution_states', ['updated_at'], unique=False)
    op.create_index(op.f('ix_strategy_execution_states_created_at'), 'strategy_execution_states', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_execution_states_enabled'), 'strategy_execution_states', ['enabled'], unique=False)
    op.create_index(op.f('ix_strategy_execution_states_id'), 'strategy_execution_states', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_execution_states_status'), 'strategy_execution_states', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_execution_states_strategy_id'), 'strategy_execution_states', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_execution_states_updated_at'), 'strategy_execution_states', ['updated_at'], unique=False)
    op.create_table('strategy_version_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_description', sa.String(length=500), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('backtest_count', sa.Integer(), nullable=True),
    sa.Column('best_backtest_pnl', sa.Float(), nullable=True),
    sa.Column('average_backtest_pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['backtest_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_version', 'strategy_version_history', ['strategy_id', 'version_number'], unique=False)
    op.create_index('idx_strategy_version_created', 'strategy_version_history', ['strategy_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_strategy_version_history_created_at'), 'strategy_version_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_version_history_id'), 'strategy_version_history', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_version_history_strategy_id'), 'strategy_version_history', ['strategy_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('num_pairs', sa.Integer(), nullable=False),
    sa.Column('total_markets', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('profitable_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('total_pnl_usd', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('starting_balance', sa.Float(), nullable=True),
    sa.Column('ending_balance', sa.Float(), nullable=True),
    sa.Column('max_balance', sa.Float(), nullable=True),
    sa.Column('min_balance', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('strategy_snapshot', sa.JSON(), nullable=True),
    sa.Column('strategy_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['backtest_strategies.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_version_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_date_range', 'backtest_runs', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_run_status_created', 'backtest_runs', ['status', 'created_at'], unique=False)
    op.create_index('idx_run_user_created', 'backtest_runs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_run_id'), 'backtest_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_version_id'), 'backtest_runs', ['strategy_version_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_user_id'), 'backtest_runs', ['user_id'], unique=False)
    op.create_table('backtest_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id_fk', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id_fk'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_candle_market_time', 'backtest_candles', ['market', 'timestamp'], unique=False)
    op.create_index('idx_backtest_candle_run_market', 'backtest_candles', ['run_id_fk', 'market'], unique=False)
    op.create_index('idx_backtest_candle_run_time', 'backtest_candles', ['run_id_fk', 'timestamp'], unique=False)
    op.create_index(op.f('ix_backtest_candles_id'), 'backtest_candles', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_candles_market'), 'backtest_candles', ['market'], unique=False)
    op.create_index(op.f('ix_backtest_candles_run_id_fk'), 'backtest_candles', ['run_id_fk'], unique=False)
    op.create_index(op.f('ix_backtest_candles_timestamp'), 'backtest_candles', ['timestamp'], unique=False)
    op.create_table('backtest_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id_1', sa.Integer(), nullable=False),
    sa.Column('strategy_id_2', sa.Integer(), nullable=False),
    sa.Column('run_id_1', sa.Integer(), nullable=False),
    sa.Column('run_id_2', sa.Integer(), nullable=False),
    sa.Column('winner_run_id', sa.Integer(), nullable=True),
    sa.Column('pnl_difference', sa.Float(), nullable=True),
    sa.Column('sharpe_difference', sa.Float(), nullable=True),
    sa.Column('win_rate_difference', sa.Float(), nullable=True),
    sa.Column('drawdown_difference', sa.Float(), nullable=True),
    sa.Column('comparison_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id_1'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['run_id_2'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['strategy_id_1'], ['backtest_strategies.id'], ),
    sa.ForeignKeyConstraint(['strategy_id_2'], ['backtest_strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comparison_runs', 'backtest_comparisons', ['run_id_1', 'run_id_2'], unique=False)
    op.create_index('idx_comparison_strategies', 'backtest_comparisons', ['strategy_id_1', 'strategy_id_2'], unique=False)
    op.create_index('idx_comparison_user_created', 'backtest_comparisons', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_backtest_comparisons_created_at'), 'backtest_comparisons', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_comparisons_id'), 'backtest_comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_comparisons_name'), 'backtest_comparisons', ['name'], unique=False)
    op.create_index(op.f('ix_backtest_comparisons_user_id'), 'backtest_comparisons', ['user_id'], unique=False)
    op.create_table('backtest_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id_fk', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id_fk'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_log_run_created', 'backtest_logs', ['run_id_fk', 'created_at'], unique=False)
    op.create_index(op.f('ix_backtest_logs_created_at'), 'backtest_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_logs_id'), 'backtest_logs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_logs_run_id_fk'), 'backtest_logs', ['run_id_fk'], unique=False)
    op.create_table('backtest_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id_fk', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=100), nullable=False),
    sa.Column('market_1', sa.String(length=50), nullable=False),
    sa.Column('market_2', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('close_timestamp', sa.DateTime(), nullable=True),
    sa.Column('entry_price_1', sa.Float(), nullable=False),
    sa.Column('entry_price_2', sa.Float(), nullable=False),
    sa.Column('entry_z_score', sa.Float(), nullable=False),
    sa.Column('current_price_1', sa.Float(), nullable=True),
    sa.Column('current_price_2', sa.Float(), nullable=True),
    sa.Column('current_z_score', sa.Float(), nullable=True),
    sa.Column('size_1', sa.Float(), nullable=False),
    sa.Column('size_2', sa.Float(), nullable=False),
    sa.Column('side_1', sa.String(length=10), nullable=False),
    sa.Column('side_2', sa.String(length=10), nullable=False),
    sa.Column('hedge_ratio', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id_fk'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_position_run_time', 'backtest_positions', ['run_id_fk', 'entry_timestamp'], unique=False)
    op.create_index('idx_backtest_position_status', 'backtest_positions', ['run_id_fk', 'status'], unique=False)
    op.create_index(op.f('ix_backtest_positions_id'), 'backtest_positions', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_positions_position_id'), 'backtest_positions', ['position_id'], unique=True)
    op.create_index(op.f('ix_backtest_positions_run_id_fk'), 'backtest_positions', ['run_id_fk'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_1', sa.String(length=50), nullable=False),
    sa.Column('market_2', sa.String(length=50), nullable=False),
    sa.Column('run_id_fk', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('entry_trades', sa.Integer(), nullable=True),
    sa.Column('exit_trades', sa.Integer(), nullable=True),
    sa.Column('profitable_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('avg_trade_duration_hours', sa.Float(), nullable=True),
    sa.Column('avg_winning_trade_duration', sa.Float(), nullable=True),
    sa.Column('avg_losing_trade_duration', sa.Float(), nullable=True),
    sa.Column('cointegration_score', sa.Float(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('zscore_mean', sa.Float(), nullable=True),
    sa.Column('zscore_std', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id_fk'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_pair', 'backtest_results', ['market_1', 'market_2'], unique=False)
    op.create_index('idx_result_run_profit', 'backtest_results', ['run_id_fk', 'pnl'], unique=False)
    op.create_index(op.f('ix_backtest_results_created_at'), 'backtest_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_results_market_1'), 'backtest_results', ['market_1'], unique=False)
    op.create_index(op.f('ix_backtest_results_market_2'), 'backtest_results', ['market_2'], unique=False)
    op.create_index(op.f('ix_backtest_results_run_id_fk'), 'backtest_results', ['run_id_fk'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id_fk', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=False),
    sa.Column('market_1', sa.String(length=50), nullable=False),
    sa.Column('market_2', sa.String(length=50), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_price_1', sa.Float(), nullable=False),
    sa.Column('entry_price_2', sa.Float(), nullable=False),
    sa.Column('entry_z_score', sa.Float(), nullable=False),
    sa.Column('side_1', sa.String(length=10), nullable=False),
    sa.Column('side_2', sa.String(length=10), nullable=False),
    sa.Column('size_1', sa.Float(), nullable=False),
    sa.Column('size_2', sa.Float(), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('exit_price_1', sa.Float(), nullable=True),
    sa.Column('exit_price_2', sa.Float(), nullable=True),
    sa.Column('exit_z_score', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('hedge_ratio', sa.Float(), nullable=False),
    sa.Column('transaction_fee', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id_fk'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_trade_market', 'backtest_trades', ['market_1', 'market_2'], unique=False)
    op.create_index('idx_backtest_trade_run_entry', 'backtest_trades', ['run_id_fk', 'entry_timestamp'], unique=False)
    op.create_index(op.f('ix_backtest_trades_entry_timestamp'), 'backtest_trades', ['entry_timestamp'], unique=False)
    op.create_index(op.f('ix_backtest_trades_exit_timestamp'), 'backtest_trades', ['exit_timestamp'], unique=False)
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_market_1'), 'backtest_trades', ['market_1'], unique=False)
    op.create_index(op.f('ix_backtest_trades_market_2'), 'backtest_trades', ['market_2'], unique=False)
    op.create_index(op.f('ix_backtest_trades_run_id_fk'), 'backtest_trades', ['run_id_fk'], unique=False)
    op.create_index(op.f('ix_backtest_trades_trade_id'), 'backtest_trades', ['trade_id'], unique=True)
    op.create_table('trade_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id_fk', sa.Integer(), nullable=False),
    sa.Column('trade_number', sa.Integer(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('entry_price_1', sa.Float(), nullable=False),
    sa.Column('entry_price_2', sa.Float(), nullable=False),
    sa.Column('exit_price_1', sa.Float(), nullable=True),
    sa.Column('exit_price_2', sa.Float(), nullable=True),
    sa.Column('quantity_1', sa.Float(), nullable=False),
    sa.Column('quantity_2', sa.Float(), nullable=False),
    sa.Column('side_1', sa.String(length=10), nullable=False),
    sa.Column('side_2', sa.String(length=10), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('entry_zscore', sa.Float(), nullable=True),
    sa.Column('exit_zscore', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id_fk'], ['backtest_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_result', 'trade_logs', ['result_id_fk', 'entry_timestamp'], unique=False)
    op.create_index(op.f('ix_trade_logs_id'), 'trade_logs', ['id'], unique=False)
    op.create_index(op.f('ix_trade_logs_result_id_fk'), 'trade_logs', ['result_id_fk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_logs_result_id_fk'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_id'), table_name='trade_logs')
    op.drop_index('idx_trade_result', table_name='trade_logs')
    op.drop_table('trade_logs')
    op.drop_index(op.f('ix_backtest_trades_trade_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_run_id_fk'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_market_2'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_market_1'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_exit_timestamp'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_entry_timestamp'), table_name='backtest_trades')
    op.drop_index('idx_backtest_trade_run_entry', table_name='backtest_trades')
    op.drop_index('idx_backtest_trade_market', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_backtest_results_run_id_fk'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_market_2'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_market_1'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_created_at'), table_name='backtest_results')
    op.drop_index('idx_result_run_profit', table_name='backtest_results')
    op.drop_index('idx_result_pair', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_backtest_positions_run_id_fk'), table_name='backtest_positions')
    op.drop_index(op.f('ix_backtest_positions_position_id'), table_name='backtest_positions')
    op.drop_index(op.f('ix_backtest_positions_id'), table_name='backtest_positions')
    op.drop_index('idx_backtest_position_status', table_name='backtest_positions')
    op.drop_index('idx_backtest_position_run_time', table_name='backtest_positions')
    op.drop_table('backtest_positions')
    op.drop_index(op.f('ix_backtest_logs_run_id_fk'), table_name='backtest_logs')
    op.drop_index(op.f('ix_backtest_logs_id'), table_name='backtest_logs')
    op.drop_index(op.f('ix_backtest_logs_created_at'), table_name='backtest_logs')
    op.drop_index('idx_backtest_log_run_created', table_name='backtest_logs')
    op.drop_table('backtest_logs')
    op.drop_index(op.f('ix_backtest_comparisons_user_id'), table_name='backtest_comparisons')
    op.drop_index(op.f('ix_backtest_comparisons_name'), table_name='backtest_comparisons')
    op.drop_index(op.f('ix_backtest_comparisons_id'), table_name='backtest_comparisons')
    op.drop_index(op.f('ix_backtest_comparisons_created_at'), table_name='backtest_comparisons')
    op.drop_index('idx_comparison_user_created', table_name='backtest_comparisons')
    op.drop_index('idx_comparison_strategies', table_name='backtest_comparisons')
    op.drop_index('idx_comparison_runs', table_name='backtest_comparisons')
    op.drop_table('backtest_comparisons')
    op.drop_index(op.f('ix_backtest_candles_timestamp'), table_name='backtest_candles')
    op.drop_index(op.f('ix_backtest_candles_run_id_fk'), table_name='backtest_candles')
    op.drop_index(op.f('ix_backtest_candles_market'), table_name='backtest_candles')
    op.drop_index(op.f('ix_backtest_candles_id'), table_name='backtest_candles')
    op.drop_index('idx_backtest_candle_run_time', table_name='backtest_candles')
    op.drop_index('idx_backtest_candle_run_market', table_name='backtest_candles')
    op.drop_index('idx_backtest_candle_market_time', table_name='backtest_candles')
    op.drop_table('backtest_candles')
    op.drop_index(op.f('ix_backtest_runs_user_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_strategy_version_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_run_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_index('idx_run_user_created', table_name='backtest_runs')
    op.drop_index('idx_run_status_created', table_name='backtest_runs')
    op.drop_index('idx_run_date_range', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_strategy_version_history_strategy_id'), table_name='strategy_version_history')
    op.drop_index(op.f('ix_strategy_version_history_id'), table_name='strategy_version_history')
    op.drop_index(op.f('ix_strategy_version_history_created_at'), table_name='strategy_version_history')
    op.drop_index('idx_strategy_version_created', table_name='strategy_version_history')
    op.drop_index('idx_strategy_version', table_name='strategy_version_history')
    op.drop_table('strategy_version_history')
    op.drop_index(op.f('ix_strategy_execution_states_updated_at'), table_name='strategy_execution_states')
    op.drop_index(op.f('ix_strategy_execution_states_strategy_id'), table_name='strategy_execution_states')
    op.drop_index(op.f('ix_strategy_execution_states_status'), table_name='strategy_execution_states')
    op.drop_index(op.f('ix_strategy_execution_states_id'), table_name='strategy_execution_states')
    op.drop_index(op.f('ix_strategy_execution_states_enabled'), table_name='strategy_execution_states')
    op.drop_index(op.f('ix_strategy_execution_states_created_at'), table_name='strategy_execution_states')
    op.drop_index('idx_execution_state_updated', table_name='strategy_execution_states')
    op.drop_index('idx_execution_state_strategy_enabled', table_name='strategy_execution_states')
    op.drop_index('idx_execution_state_status', table_name='strategy_execution_states')
    op.drop_table('strategy_execution_states')
    op.drop_index(op.f('ix_dydx_keys_user_id'), table_name='dydx_keys')
    op.drop_index(op.f('ix_dydx_keys_network'), table_name='dydx_keys')
    op.drop_index(op.f('ix_dydx_keys_id'), table_name='dydx_keys')
    op.drop_table('dydx_keys')
    op.drop_index(op.f('ix_dydx_key_settings_user_id'), table_name='dydx_key_settings')
    op.drop_index(op.f('ix_dydx_key_settings_id'), table_name='dydx_key_settings')
    op.drop_table('dydx_key_settings')
    op.drop_index(op.f('ix_bot_settings_section'), table_name='bot_settings')
    op.drop_index(op.f('ix_bot_settings_key'), table_name='bot_settings')
    op.drop_index(op.f('ix_bot_settings_is_active'), table_name='bot_settings')
    op.drop_index(op.f('ix_bot_settings_id'), table_name='bot_settings')
    op.drop_index('idx_bot_setting_section_key', table_name='bot_settings')
    op.drop_index('idx_bot_setting_active', table_name='bot_settings')
    op.drop_table('bot_settings')
    op.drop_index(op.f('ix_backtest_strategies_user_id'), table_name='backtest_strategies')
    op.drop_index(op.f('ix_backtest_strategies_name'), table_name='backtest_strategies')
    op.drop_index(op.f('ix_backtest_strategies_id'), table_name='backtest_strategies')
    op.drop_index(op.f('ix_backtest_strategies_created_at'), table_name='backtest_strategies')
    op.drop_index('idx_strategy_user_name', table_name='backtest_strategies')
    op.drop_index('idx_strategy_public', table_name='backtest_strategies')
    op.drop_index('idx_strategy_default', table_name='backtest_strategies')
    op.drop_index('idx_strategy_category', table_name='backtest_strategies')
    op.drop_table('backtest_strategies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_redis_settings_id'), table_name='redis_settings')
    op.drop_index(op.f('ix_redis_settings_enabled'), table_name='redis_settings')
    op.drop_index('idx_redis_enabled', table_name='redis_settings')
    op.drop_table('redis_settings')
    # ### end Alembic commands ###
